import React, { useState, useEffect, useRef } from 'react';
import { 
  FaBookOpen, 
  FaBrain, 
  FaGraduationCap,
  FaLightbulb,
  FaUsers,
  FaChartLine
} from 'react-icons/fa';

interface IntroductionSectionProps {
  className?: string;
  isDark?: boolean;
}

export const IntroductionSection: React.FC<IntroductionSectionProps> = ({ className = "", isDark = false }) => {
  const [isVisible, setIsVisible] = useState(false);
  const [currentParagraph, setCurrentParagraph] = useState(0);
  const sectionRef = useRef<HTMLDivElement>(null);

  const paragraphs = React.useMemo(() => [
    {
      icon: <FaBookOpen className="w-6 h-6" />,
      title: "Revolutionizing Education Through AI",
      content: "PrepToDo is a cutting-edge educational platform that harnesses the power of artificial intelligence to create personalized learning experiences. Even though all our study materials are generated by AI, our platform excels in the way it analyzes and helps users grow overall.",
      gradient: isDark ? "from-academic-primary-dark to-brand-primary-dark" : "from-academic-primary-light to-brand-primary-light"
    },
    {
      icon: <FaBrain className="w-6 h-6" />,
      title: "Adaptive Learning Intelligence", 
      content: "Our sophisticated algorithms don't just create content—they understand your unique learning style, track your progress in real-time, and adapt your study journey to maximize retention and performance. Every interaction is designed to build upon your existing knowledge while identifying and strengthening weak areas.",
      gradient: isDark ? "from-academic-secondary-dark to-brand-secondary-dark" : "from-academic-secondary-light to-brand-secondary-light"
    },
    {
      icon: <FaGraduationCap className="w-6 h-6" />,
      title: "Transformative Study Experience",
      content: "The result? A study experience that's not just personalized, but truly transformative—helping you achieve better grades, deeper understanding, and lasting knowledge retention.",
      gradient: isDark ? "from-academic-accent-dark to-brand-accent-dark" : "from-academic-accent-light to-brand-accent-light",
      isHighlight: true
    }
  ], [isDark]);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
          // Animate paragraphs with delay
          paragraphs.forEach((_, index) => {
            setTimeout(() => {
              setCurrentParagraph(index);
            }, index * 800);
          });
        }
      },
      { threshold: 0.3 }
    );

    if (sectionRef.current) {
      observer.observe(sectionRef.current);
    }

    return () => observer.disconnect();
  }, [paragraphs]);

  return (
    <section 
      ref={sectionRef}
      className={`relative py-24 overflow-hidden bg-gradient-to-b from-bg-secondary-light to-bg-tertiary-light dark:from-bg-secondary-dark dark:to-bg-tertiary-dark ${className}`}
    >
      
      {/* Background Elements */}
      <div className="absolute inset-0 overflow-hidden">
        {/* Animated background shapes */}
        <div className={`absolute top-1/4 left-1/4 w-96 h-96 rounded-full blur-3xl animate-float ${isDark ? 'bg-gradient-to-br from-brand-primary-dark/20 to-brand-primary-dark/20' : 'bg-gradient-to-br from-brand-primary-light/10 to-brand-primary-light/10'}`} style={{ animationDelay: '0s', animationDuration: '8s' }} />
        <div className={`absolute bottom-1/4 right-1/4 w-80 h-80 rounded-full blur-3xl animate-float ${isDark ? 'bg-gradient-to-br from-brand-secondary-dark/20 to-brand-secondary-dark/20' : 'bg-gradient-to-br from-brand-secondary-light/10 to-brand-secondary-light/10'}`} style={{ animationDelay: '3s', animationDuration: '10s' }} />
        
        {/* Floating geometric elements */}
        <div className={`absolute top-1/3 right-10 w-2 h-20 rounded-full transform rotate-45 animate-bounce-subtle ${isDark ? 'bg-gradient-to-b from-academic-primary-dark/40 to-transparent' : 'bg-gradient-to-b from-academic-primary-light/30 to-transparent'}`} style={{ animationDelay: '1s' }} />
        <div className={`absolute bottom-1/3 left-10 w-2 h-16 rounded-full transform -rotate-45 animate-bounce-subtle ${isDark ? 'bg-gradient-to-b from-brand-secondary-dark/40 to-transparent' : 'bg-gradient-to-b from-brand-secondary-light/30 to-transparent'}`} style={{ animationDelay: '2s' }} />
      </div>

      <div className="relative max-w-6xl mx-auto px-6">
        
        {/* Section Header */}
        <div className={`
          text-center mb-16 transition-all duration-1000 ease-out
          ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}
        `}>
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-academic-primary-light/10 dark:bg-academic-primary-dark/20 border border-academic-primary-light/20 dark:border-academic-primary-dark/30 backdrop-blur-sm mb-6">
            <div className="w-2 h-2 bg-academic-primary-light dark:bg-academic-primary-dark rounded-full animate-pulse-soft" />
            <span className="text-sm font-medium text-academic-primary-light dark:text-academic-primary-dark">
              About PrepToDo
            </span>
          </div>
          
          <h2 className="text-4xl lg:text-5xl font-serif font-bold mb-6">
            <span className="bg-gradient-to-r from-text-primary-light via-academic-primary-light to-brand-primary-light dark:from-text-primary-dark dark:via-academic-primary-dark dark:to-brand-primary-dark bg-clip-text text-transparent">
              Why Students Choose
            </span>
            <br />
            <span className="bg-gradient-to-r from-brand-secondary-light to-brand-accent-light dark:from-brand-secondary-dark dark:to-brand-accent-dark bg-clip-text text-transparent">
              PrepToDo
            </span>
          </h2>
          
          <div className="w-24 h-1 bg-gradient-to-r from-academic-primary-light to-brand-primary-light dark:from-academic-primary-dark dark:to-brand-primary-dark mx-auto rounded-full" />
        </div>

        {/* Content */}
        <div className="space-y-12 lg:space-y-16">
          {paragraphs.map((paragraph, index) => (
            <div
              key={index}
              className={`
                relative transition-all duration-1000 ease-out
                ${isVisible && currentParagraph >= index 
                  ? 'opacity-100 translate-y-0' 
                  : 'opacity-0 translate-y-12'
                }
              `}
              style={{ transitionDelay: `${index * 200}ms` }}
            >
              <div className={`
                max-w-4xl mx-auto p-8 lg:p-12 rounded-3xl border border-border-light dark:border-border-dark
                bg-bg-primary-light/60 dark:bg-bg-secondary-dark/60 backdrop-blur-sm shadow-lg hover:shadow-xl
                transition-all duration-500 group
                ${paragraph.isHighlight ? 'border-academic-accent-light/50 dark:border-academic-accent-dark/50 bg-gradient-to-br from-bg-secondary-light/50 to-bg-tertiary-light/30 dark:from-bg-secondary-dark/10 dark:to-bg-tertiary-dark/5' : ''}
              `}>
                
                {/* Paragraph content */}
                <div className="relative z-10">
                  <div className="flex items-start gap-6">
                    
                    {/* Icon indicator */}
                    <div className={`
                      relative w-16 h-16 rounded-2xl flex items-center justify-center text-white
                      bg-gradient-to-br ${paragraph.gradient} shadow-lg
                      transform group-hover:scale-110 transition-transform duration-300
                      flex-shrink-0
                    `}>
                      <span className="relative z-10">{paragraph.icon}</span>
                      
                      {/* Glow effect */}
                      <div className={`
                        absolute inset-0 rounded-2xl bg-gradient-to-br ${paragraph.gradient}
                        blur-lg opacity-0 group-hover:opacity-40 transition-opacity duration-300
                      `} />
                    </div>

                    {/* Text content */}
                    <div className="flex-1 space-y-4">
                      <h3 className={`
                        text-2xl lg:text-3xl font-bold
                        bg-gradient-to-r ${paragraph.gradient} bg-clip-text text-transparent
                        group-hover:scale-105 transition-transform duration-300
                      `}>
                        {paragraph.title}
                      </h3>
                      
                      <p className={`
                        text-lg lg:text-xl leading-relaxed transition-colors duration-300
                        ${paragraph.isHighlight 
                          ? 'text-accent-700 dark:text-accent-300 font-medium' 
                          : 'text-text-secondary'
                        }
                      `}>
                        {paragraph.content}
                      </p>
                    </div>
                  </div>
                </div>

                {/* Decorative elements */}
                <div className={`
                  absolute top-4 right-4 w-8 h-8 rounded-full border-2
                  bg-gradient-to-br ${paragraph.gradient} opacity-20
                  group-hover:opacity-40 transition-opacity duration-300
                `} />
                
                <div className={`
                  absolute bottom-4 left-4 w-6 h-6 rounded-full
                  bg-gradient-to-br ${paragraph.gradient} opacity-10
                  group-hover:opacity-30 transition-opacity duration-300 animate-bounce-subtle
                `} />
              </div>
            </div>
          ))}
        </div>

        {/* Interactive Statistics */}
        <div className={`
          mt-20 p-8 lg:p-12 rounded-3xl border border-border-light dark:border-border-dark
          bg-gradient-to-br from-bg-primary-light/80 to-bg-secondary-light/80 dark:from-bg-secondary-dark/80 dark:to-bg-tertiary-dark/80
          backdrop-blur-sm shadow-lg
          transition-all duration-1000 ease-out delay-1000
          ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}
        `}>
          
          <div className="text-center mb-8">
            <h3 className="text-3xl lg:text-4xl font-bold text-text-primary-light dark:text-text-primary-dark mb-4">
              Trusted by Students Worldwide
            </h3>
            <p className="text-lg text-text-secondary-light dark:text-text-secondary-dark">
              Join thousands of successful learners who have transformed their academic journey
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 lg:gap-12">
            <div className="text-center space-y-2">
              <div className="flex justify-center mb-4">
                <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-academic-success-light to-brand-secondary-light dark:from-academic-success-dark dark:to-brand-secondary-dark flex items-center justify-center">
                  <FaUsers className="w-8 h-8 text-white" />
                </div>
              </div>
              <div className="text-4xl lg:text-5xl font-bold bg-gradient-to-r from-academic-success-light to-brand-secondary-light dark:from-academic-success-dark dark:to-brand-secondary-dark bg-clip-text text-transparent">
                95%
              </div>
              <div className="text-text-muted-light dark:text-text-muted-dark font-medium">
                Student Satisfaction Rate
              </div>
              <div className="w-16 h-1 bg-gradient-to-r from-academic-success-light to-brand-secondary-light dark:from-academic-success-dark dark:to-brand-secondary-dark mx-auto rounded-full mt-3" />
            </div>
            
            <div className="text-center space-y-2">
              <div className="flex justify-center mb-4">
                <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-academic-primary-light to-brand-primary-light dark:from-academic-primary-dark dark:to-brand-primary-dark flex items-center justify-center">
                  <FaChartLine className="w-8 h-8 text-white" />
                </div>
              </div>
              <div className="text-4xl lg:text-5xl font-bold bg-gradient-to-r from-academic-primary-light to-brand-primary-light dark:from-academic-primary-dark dark:to-brand-primary-dark bg-clip-text text-transparent">
                2x
              </div>
              <div className="text-text-muted-light dark:text-text-muted-dark font-medium">
                Faster Learning Speed
              </div>
              <div className="w-16 h-1 bg-gradient-to-r from-academic-primary-light to-brand-primary-light dark:from-academic-primary-dark dark:to-brand-primary-dark mx-auto rounded-full mt-3" />
            </div>
            
            <div className="text-center space-y-2">
              <div className="flex justify-center mb-4">
                <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-academic-accent-light to-brand-accent-light dark:from-academic-accent-dark dark:to-brand-accent-dark flex items-center justify-center">
                  <FaLightbulb className="w-8 h-8 text-white" />
                </div>
              </div>
              <div className="text-4xl lg:text-5xl font-bold bg-gradient-to-r from-academic-accent-light to-brand-accent-light dark:from-academic-accent-dark dark:to-brand-accent-dark bg-clip-text text-transparent">
                24/7
              </div>
              <div className="text-text-muted-light dark:text-text-muted-dark font-medium">
                AI-Powered Support
              </div>
              <div className="w-16 h-1 bg-gradient-to-r from-academic-accent-light to-brand-accent-light dark:from-academic-accent-dark dark:to-brand-accent-dark mx-auto rounded-full mt-3" />
            </div>
          </div>
        </div>

        {/* Bottom decoration */}
        <div className="text-center mt-16">
          <div className="inline-flex items-center gap-2 text-text-muted-light dark:text-text-muted-dark">
            <div className="w-2 h-2 bg-academic-success-light dark:bg-academic-success-dark rounded-full animate-pulse-soft" />
            <span className="text-sm font-medium">Experience the future of learning</span>
            <div className="w-2 h-2 bg-brand-secondary-light dark:bg-brand-secondary-dark rounded-full animate-pulse-soft" style={{ animationDelay: '0.5s' }} />
          </div>
        </div>
      </div>
    </section>
  );
};