import React, { useState, useEffect, useRef } from 'react';

interface IntroductionSectionProps {
  className?: string;
}

export const IntroductionSection: React.FC<IntroductionSectionProps> = ({ className = "" }) => {
  const [isVisible, setIsVisible] = useState(false);
  const [currentParagraph, setCurrentParagraph] = useState(0);
  const sectionRef = useRef<HTMLDivElement>(null);

  const paragraphs = React.useMemo(() => [
    {
      title: "Revolutionizing Education Through AI",
      content: "PrepToDo is a cutting-edge educational platform that harnesses the power of artificial intelligence to create personalized learning experiences. Even though all our study materials are generated by AI, our platform excels in the way it analyzes and helps users grow overall.",
      gradient: "from-primary-500 to-violet-500"
    },
    {
      title: "Adaptive Learning Intelligence",
      content: "Our sophisticated algorithms don't just create content—they understand your unique learning style, track your progress in real-time, and adapt your study journey to maximize retention and performance. Every interaction is designed to build upon your existing knowledge while identifying and strengthening weak areas.",
      gradient: "from-secondary-500 to-teal-500"
    },
    {
      title: "Transformative Study Experience",
      content: "✨ The result? A study experience that's not just personalized, but truly transformative—helping you achieve better grades, deeper understanding, and lasting knowledge retention.",
      gradient: "from-accent-500 to-amber-500",
      isHighlight: true
    }
  ], []);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
          // Animate paragraphs with delay
          paragraphs.forEach((_, index) => {
            setTimeout(() => {
              setCurrentParagraph(index);
            }, index * 800);
          });
        }
      },
      { threshold: 0.3 }
    );

    if (sectionRef.current) {
      observer.observe(sectionRef.current);
    }

    return () => observer.disconnect();
  }, [paragraphs]);

  return (
    <section 
      ref={sectionRef}
      className={`relative py-24 overflow-hidden bg-gradient-to-b from-white to-gray-50/50 dark:from-slate-800 dark:to-slate-900 ${className}`}
    >
      
      {/* Background Elements */}
      <div className="absolute inset-0 overflow-hidden">
        {/* Animated background shapes */}
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-gradient-to-br from-blue-400/10 to-purple-400/10 dark:from-blue-600/20 dark:to-purple-600/20 rounded-full blur-3xl animate-float" style={{ animationDelay: '0s', animationDuration: '8s' }} />
        <div className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-gradient-to-br from-teal-400/10 to-cyan-400/10 dark:from-teal-600/20 dark:to-cyan-600/20 rounded-full blur-3xl animate-float" style={{ animationDelay: '3s', animationDuration: '10s' }} />
        
        {/* Floating geometric elements */}
        <div className="absolute top-1/3 right-10 w-2 h-20 bg-gradient-to-b from-blue-400/30 to-transparent dark:from-blue-500/40 rounded-full transform rotate-45 animate-bounce-subtle" style={{ animationDelay: '1s' }} />
        <div className="absolute bottom-1/3 left-10 w-2 h-16 bg-gradient-to-b from-teal-400/30 to-transparent dark:from-teal-500/40 rounded-full transform -rotate-45 animate-bounce-subtle" style={{ animationDelay: '2s' }} />
      </div>

      <div className="relative max-w-6xl mx-auto px-6">
        
        {/* Section Header */}
        <div className={`
          text-center mb-16 transition-all duration-1000 ease-out
          ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}
        `}>
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-100/80 dark:bg-blue-900/30 border border-blue-200/50 dark:border-blue-700/50 backdrop-blur-sm mb-6">
            <div className="w-2 h-2 bg-blue-500 rounded-full animate-pulse-soft" />
            <span className="text-sm font-medium text-blue-700 dark:text-blue-300">
              About PrepToDo
            </span>
          </div>
          
          <h2 className="text-4xl lg:text-5xl font-serif font-bold mb-6">
            <span className="bg-gradient-to-r from-gray-900 via-blue-600 to-purple-600 dark:from-white dark:via-blue-400 dark:to-purple-400 bg-clip-text text-transparent">
              Why Students Choose
            </span>
            <br />
            <span className="bg-gradient-to-r from-teal-600 to-amber-600 dark:from-teal-400 dark:to-amber-400 bg-clip-text text-transparent">
              PrepToDo
            </span>
          </h2>
          
          <div className="w-24 h-1 bg-gradient-to-r from-blue-500 to-purple-500 mx-auto rounded-full" />
        </div>

        {/* Content */}
        <div className="space-y-12 lg:space-y-16">
          {paragraphs.map((paragraph, index) => (
            <div
              key={index}
              className={`
                relative transition-all duration-1000 ease-out
                ${isVisible && currentParagraph >= index 
                  ? 'opacity-100 translate-y-0' 
                  : 'opacity-0 translate-y-12'
                }
              `}
              style={{ transitionDelay: `${index * 200}ms` }}
            >
              <div className={`
                max-w-4xl mx-auto p-8 lg:p-12 rounded-3xl border border-border/30 dark:border-surface-600/30
                bg-white/60 dark:bg-surface-800/60 backdrop-blur-sm shadow-card-lg hover:shadow-card-xl
                transition-all duration-500 group
                ${paragraph.isHighlight ? 'border-accent-200/50 dark:border-accent-700/50 bg-gradient-to-br from-accent-50/50 to-amber-50/30 dark:from-accent-900/10 dark:to-amber-900/5' : ''}
              `}>
                
                {/* Paragraph content */}
                <div className="relative z-10">
                  <div className="flex items-start gap-6">
                    
                    {/* Number indicator */}
                    <div className={`
                      relative w-12 h-12 rounded-2xl flex items-center justify-center font-bold text-lg
                      bg-gradient-to-br ${paragraph.gradient} text-white shadow-lg
                      transform group-hover:scale-110 transition-transform duration-300
                      flex-shrink-0
                    `}>
                      <span className="relative z-10">{index + 1}</span>
                      
                      {/* Glow effect */}
                      <div className={`
                        absolute inset-0 rounded-2xl bg-gradient-to-br ${paragraph.gradient}
                        blur-lg opacity-0 group-hover:opacity-40 transition-opacity duration-300
                      `} />
                    </div>

                    {/* Text content */}
                    <div className="flex-1 space-y-4">
                      <h3 className={`
                        text-2xl lg:text-3xl font-bold
                        bg-gradient-to-r ${paragraph.gradient} bg-clip-text text-transparent
                        group-hover:scale-105 transition-transform duration-300
                      `}>
                        {paragraph.title}
                      </h3>
                      
                      <p className={`
                        text-lg lg:text-xl leading-relaxed transition-colors duration-300
                        ${paragraph.isHighlight 
                          ? 'text-accent-700 dark:text-accent-300 font-medium' 
                          : 'text-text-secondary'
                        }
                      `}>
                        {paragraph.content}
                      </p>
                    </div>
                  </div>
                </div>

                {/* Decorative elements */}
                <div className={`
                  absolute top-4 right-4 w-8 h-8 rounded-full border-2
                  bg-gradient-to-br ${paragraph.gradient} opacity-20
                  group-hover:opacity-40 transition-opacity duration-300
                `} />
                
                <div className={`
                  absolute bottom-4 left-4 w-6 h-6 rounded-full
                  bg-gradient-to-br ${paragraph.gradient} opacity-10
                  group-hover:opacity-30 transition-opacity duration-300 animate-bounce-subtle
                `} />
              </div>
            </div>
          ))}
        </div>

        {/* Interactive Statistics */}
        <div className={`
          mt-20 p-8 lg:p-12 rounded-3xl border border-border/30 dark:border-surface-600/30
          bg-gradient-to-br from-white/80 to-surface-100/80 dark:from-surface-800/80 dark:to-surface-700/80
          backdrop-blur-sm shadow-card-lg
          transition-all duration-1000 ease-out delay-1000
          ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}
        `}>
          
          <div className="text-center mb-8">
            <h3 className="text-3xl lg:text-4xl font-bold text-text-primary mb-4">
              Trusted by Students Worldwide
            </h3>
            <p className="text-lg text-text-muted">
              Join thousands of successful learners who have transformed their academic journey
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 lg:gap-12">
            <div className="text-center space-y-2">
              <div className="text-4xl lg:text-5xl font-bold bg-gradient-to-r from-primary-500 to-violet-500 bg-clip-text text-transparent animate-count-up">
                95%
              </div>
              <div className="text-text-muted font-medium">
                Student Satisfaction Rate
              </div>
              <div className="w-16 h-1 bg-gradient-primary mx-auto rounded-full mt-3" />
            </div>
            
            <div className="text-center space-y-2">
              <div className="text-4xl lg:text-5xl font-bold bg-gradient-to-r from-secondary-500 to-teal-500 bg-clip-text text-transparent animate-count-up delay-200">
                2x
              </div>
              <div className="text-text-muted font-medium">
                Faster Learning Speed
              </div>
              <div className="w-16 h-1 bg-gradient-secondary mx-auto rounded-full mt-3" />
            </div>
            
            <div className="text-center space-y-2">
              <div className="text-4xl lg:text-5xl font-bold bg-gradient-to-r from-accent-500 to-amber-500 bg-clip-text text-transparent animate-count-up delay-400">
                24/7
              </div>
              <div className="text-text-muted font-medium">
                AI-Powered Support
              </div>
              <div className="w-16 h-1 bg-gradient-accent mx-auto rounded-full mt-3" />
            </div>
          </div>
        </div>

        {/* Bottom decoration */}
        <div className="text-center mt-16">
          <div className="inline-flex items-center gap-2 text-text-muted">
            <div className="w-2 h-2 bg-primary-400 rounded-full animate-pulse-soft" />
            <span className="text-sm font-medium">Experience the future of learning</span>
            <div className="w-2 h-2 bg-secondary-400 rounded-full animate-pulse-soft" style={{ animationDelay: '0.5s' }} />
          </div>
        </div>
      </div>
    </section>
  );
};