// supabase/functions/daily-content-init/index.ts

import "jsr:@supabase/functions-js/edge-runtime.d.ts"

// Import from the pre-bundled file
// This file will be auto-generated by: npm run bundle:daily-content
import { handleStep1Init } from "./bundled.ts"

console.log("daily-content-init function loaded")

// Define standard CORS headers
export const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

Deno.serve(async (req: Request) => {
  // Handle Preflight (OPTIONS) requests explicitly
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    if (req.method !== "POST") {
      return new Response(
        JSON.stringify({ error: "Method Not Allowed" }),
        {
          status: 405,
          headers: { ...corsHeaders, "Content-Type": "application/json" }
        }
      )
    }

    const payload = await req.json()
    console.log("📥 Received request for daily-content-init")

    // Run step 1 handler
    const result = await handleStep1Init(payload)

    return new Response(
      JSON.stringify({
        success: true,
        data: result
      }),
      {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" }
      }
    )

  } catch (err) {
    console.error("❌ daily-content-init error:", err)

    return new Response(
      JSON.stringify({
        error: "Daily content initialization failed",
        details: err instanceof Error ? err.message : String(err)
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" }
      }
    )
  }
})