-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.articles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title text,
  url text NOT NULL UNIQUE,
  source_name text,
  author text,
  published_at date,
  genre text NOT NULL,
  topic_tags ARRAY,
  used_in_daily boolean DEFAULT false,
  used_in_custom_exam boolean DEFAULT false,
  daily_usage_count integer DEFAULT 0,
  custom_exam_usage_count integer DEFAULT 0,
  last_used_at timestamp with time zone,
  semantic_hash text,
  extraction_model text,
  extraction_version text,
  is_safe_source boolean DEFAULT true,
  is_archived boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT articles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.content_appeals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  appeal_type character varying NOT NULL CHECK (appeal_type::text = ANY (ARRAY['question'::character varying, 'passage'::character varying, 'rationale'::character varying, 'vocab'::character varying]::text[])),
  target_id uuid NOT NULL,
  user_id uuid NOT NULL,
  reason character varying NOT NULL,
  description text NOT NULL,
  suggested_correction text,
  attempt_id uuid,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'under_review'::character varying, 'ai_response_sent'::character varying, 'resolved'::character varying, 'escalated'::character varying, 'rejected'::character varying]::text[])),
  ai_response text,
  ai_response_sent_at timestamp with time zone,
  reviewer_id uuid,
  reviewer_notes text,
  resolution text,
  resolved_at timestamp with time zone,
  appeal_accepted boolean,
  correction_applied boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT content_appeals_pkey PRIMARY KEY (id),
  CONSTRAINT content_appeals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT content_appeals_attempt_id_fkey FOREIGN KEY (attempt_id) REFERENCES public.question_attempts(id),
  CONSTRAINT content_appeals_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.content_review_queue (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  content_type character varying NOT NULL CHECK (content_type::text = ANY (ARRAY['passage'::character varying, 'question'::character varying, 'vocab'::character varying, 'appeal'::character varying]::text[])),
  content_id uuid NOT NULL,
  priority integer DEFAULT 5 CHECK (priority >= 1 AND priority <= 10),
  review_reason character varying,
  assigned_to uuid,
  assigned_at timestamp with time zone,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'assigned'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  review_notes text,
  action_taken character varying,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT content_review_queue_pkey PRIMARY KEY (id),
  CONSTRAINT content_review_queue_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.core_metrics (
  key text NOT NULL,
  description text NOT NULL,
  version text NOT NULL DEFAULT 'v1.0'::text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  mapping_logic text NOT NULL,
  CONSTRAINT core_metrics_pkey PRIMARY KEY (key)
);
CREATE TABLE public.daily_challenges (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  challenge_date date NOT NULL UNIQUE,
  title character varying NOT NULL,
  description text,
  passage_ids ARRAY NOT NULL,
  target_time_minutes integer,
  difficulty_mix character varying,
  participants_count integer DEFAULT 0,
  avg_score numeric,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT daily_challenges_pkey PRIMARY KEY (id)
);
CREATE TABLE public.embeddings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  embedding USER-DEFINED NOT NULL,
  embedding_model text DEFAULT 'text-embedding-3-small'::text,
  theory_id uuid,
  passage_id uuid,
  question_id uuid,
  content_preview text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT embeddings_pkey PRIMARY KEY (id),
  CONSTRAINT embeddings_theory_id_fkey FOREIGN KEY (theory_id) REFERENCES public.theory_chunks(id),
  CONSTRAINT embeddings_passage_id_fkey FOREIGN KEY (passage_id) REFERENCES public.passages(id),
  CONSTRAINT embeddings_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions(id)
);
CREATE TABLE public.error_patterns (
  key text NOT NULL,
  description text NOT NULL,
  severity integer CHECK (severity >= 1 AND severity <= 5),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT error_patterns_pkey PRIMARY KEY (key)
);
CREATE TABLE public.exam_papers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  year integer NOT NULL,
  exam_type text DEFAULT 'CAT'::text,
  slot text,
  is_official boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  used_articles_id ARRAY,
  genereted_by_user_id uuid,
  CONSTRAINT exam_papers_pkey PRIMARY KEY (id),
  CONSTRAINT exam_papers_genereted_by_user_id_fkey FOREIGN KEY (genereted_by_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.feature_flags (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  flag_key character varying NOT NULL UNIQUE,
  flag_name character varying NOT NULL,
  description text,
  is_enabled boolean DEFAULT false,
  rollout_percentage integer DEFAULT 0 CHECK (rollout_percentage >= 0 AND rollout_percentage <= 100),
  enabled_for_users ARRAY,
  enabled_for_tiers ARRAY,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT feature_flags_pkey PRIMARY KEY (id),
  CONSTRAINT feature_flags_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.generation_cache (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  cache_key character varying NOT NULL UNIQUE,
  request_type character varying NOT NULL,
  request_params jsonb NOT NULL,
  result_data jsonb NOT NULL,
  result_ids ARRAY,
  generation_model character varying,
  generation_cost_cents integer,
  hit_count integer DEFAULT 0,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_accessed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT generation_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.genres (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  description text,
  daily_usage_count integer DEFAULT 0,
  custom_exam_usage_count integer DEFAULT 0,
  total_usage_count integer DEFAULT (daily_usage_count + custom_exam_usage_count),
  last_used_daily_at timestamp with time zone,
  last_used_custom_exam_at timestamp with time zone,
  cooldown_days integer DEFAULT 2,
  avg_difficulty_score numeric,
  preferred_question_types ARRAY,
  is_active boolean DEFAULT true,
  is_high_priority boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT genres_pkey PRIMARY KEY (id)
);
CREATE TABLE public.graph_edges (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  source_node_id uuid,
  target_node_id uuid,
  relationship text,
  CONSTRAINT graph_edges_pkey PRIMARY KEY (id),
  CONSTRAINT graph_edges_target_node_id_fkey FOREIGN KEY (target_node_id) REFERENCES public.graph_nodes(id),
  CONSTRAINT graph_edges_source_node_id_fkey FOREIGN KEY (source_node_id) REFERENCES public.graph_nodes(id)
);
CREATE TABLE public.graph_nodes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  label text UNIQUE,
  type text,
  CONSTRAINT graph_nodes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.group_chat_messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  group_id uuid NOT NULL,
  user_id uuid NOT NULL,
  message_type character varying DEFAULT 'text'::character varying CHECK (message_type::text = ANY (ARRAY['text'::character varying, 'image'::character varying, 'challenge'::character varying, 'achievement'::character varying]::text[])),
  content text NOT NULL,
  attachments jsonb,
  is_edited boolean DEFAULT false,
  edited_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT group_chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT group_chat_messages_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.study_groups(id),
  CONSTRAINT group_chat_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.leaderboard_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  leaderboard_type character varying NOT NULL CHECK (leaderboard_type::text = ANY (ARRAY['daily'::character varying, 'weekly'::character varying, 'monthly'::character varying, 'all_time'::character varying, 'genre_specific'::character varying]::text[])),
  period_start date NOT NULL,
  period_end date NOT NULL,
  genre character varying,
  user_id uuid NOT NULL,
  rank integer NOT NULL,
  score integer NOT NULL,
  questions_attempted integer DEFAULT 0,
  accuracy_percentage numeric,
  avg_time_per_question integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leaderboard_entries_pkey PRIMARY KEY (id),
  CONSTRAINT leaderboard_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.passages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title character varying,
  content text NOT NULL,
  word_count integer NOT NULL,
  genre character varying NOT NULL,
  difficulty character varying NOT NULL CHECK (difficulty::text = ANY (ARRAY['easy'::character varying, 'medium'::character varying, 'hard'::character varying]::text[])),
  source character varying,
  generation_model character varying,
  generation_prompt_version character varying,
  generation_cost_cents integer,
  quality_score numeric,
  times_used integer DEFAULT 0,
  avg_completion_time_seconds integer,
  avg_accuracy numeric,
  is_daily_pick boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  is_archived boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  paper_id uuid,
  CONSTRAINT passages_pkey PRIMARY KEY (id),
  CONSTRAINT passages_paper_id_fkey FOREIGN KEY (paper_id) REFERENCES public.exam_papers(id)
);
CREATE TABLE public.peer_challenges (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  challenger_id uuid NOT NULL,
  challenged_user_id uuid NOT NULL,
  challenge_type character varying CHECK (challenge_type::text = ANY (ARRAY['accuracy'::character varying, 'speed'::character varying, 'streak'::character varying, 'specific_topic'::character varying]::text[])),
  question_ids ARRAY,
  passage_ids ARRAY,
  time_limit_seconds integer,
  target_accuracy numeric,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'declined'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'expired'::character varying]::text[])),
  challenger_session_id uuid,
  challenged_session_id uuid,
  winner_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT peer_challenges_pkey PRIMARY KEY (id),
  CONSTRAINT peer_challenges_challenger_id_fkey FOREIGN KEY (challenger_id) REFERENCES public.user_profiles(id),
  CONSTRAINT peer_challenges_challenged_user_id_fkey FOREIGN KEY (challenged_user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT peer_challenges_challenger_session_id_fkey FOREIGN KEY (challenger_session_id) REFERENCES public.practice_sessions(id),
  CONSTRAINT peer_challenges_challenged_session_id_fkey FOREIGN KEY (challenged_session_id) REFERENCES public.practice_sessions(id),
  CONSTRAINT peer_challenges_winner_id_fkey FOREIGN KEY (winner_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.practice_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  session_type character varying NOT NULL CHECK (session_type::text = ANY (ARRAY['practice'::character varying::text, 'timed_test'::character varying::text, 'daily_challenge_rc'::character varying::text, 'daily_challenge_va'::character varying::text, 'mock_exam'::character varying::text, 'vocab_review'::character varying::text, 'microlearning'::character varying::text, 'drill'::character varying::text, 'group_practice'::character varying::text])),
  mode character varying CHECK (mode::text = ANY (ARRAY['tutor'::character varying, 'test'::character varying, 'adaptive'::character varying]::text[])),
  passage_ids ARRAY,
  question_ids ARRAY,
  target_difficulty character varying,
  target_genres ARRAY,
  target_question_types ARRAY,
  time_limit_seconds integer,
  time_spent_seconds integer DEFAULT 0,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  paused_at timestamp with time zone,
  pause_duration_seconds integer DEFAULT 0,
  total_questions integer DEFAULT 0,
  correct_answers integer DEFAULT 0,
  score_percentage numeric,
  points_earned integer DEFAULT 0,
  status character varying DEFAULT 'in_progress'::character varying CHECK (status::text = ANY (ARRAY['in_progress'::character varying, 'completed'::character varying, 'abandoned'::character varying, 'paused'::character varying]::text[])),
  current_question_index integer DEFAULT 0,
  session_data jsonb,
  is_group_session boolean DEFAULT false,
  group_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  paper_id uuid,
  is_analysed boolean DEFAULT false,
  analytics jsonb,
  CONSTRAINT practice_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT practice_sessions_paper_id_fkey FOREIGN KEY (paper_id) REFERENCES public.exam_papers(id),
  CONSTRAINT practice_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT practice_sessions_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.study_groups(id)
);
CREATE TABLE public.question_attempts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  session_id uuid NOT NULL,
  question_id uuid NOT NULL,
  passage_id uuid,
  user_answer jsonb,
  is_correct boolean NOT NULL,
  time_spent_seconds integer NOT NULL,
  confidence_level integer CHECK (confidence_level >= 1 AND confidence_level <= 5),
  marked_for_review boolean DEFAULT false,
  eliminated_options ARRAY,
  hint_used boolean DEFAULT false,
  hints_viewed integer DEFAULT 0,
  rationale_viewed boolean DEFAULT false,
  rationale_helpful boolean,
  user_notes text,
  ai_grading_score numeric,
  ai_feedback text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT question_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT question_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT question_attempts_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.practice_sessions(id),
  CONSTRAINT question_attempts_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions(id),
  CONSTRAINT question_attempts_passage_id_fkey FOREIGN KEY (passage_id) REFERENCES public.passages(id)
);
CREATE TABLE public.question_types (
  key text NOT NULL,
  description text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT question_types_pkey PRIMARY KEY (key)
);
CREATE TABLE public.questions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  passage_id uuid,
  question_text text NOT NULL,
  question_type character varying NOT NULL CHECK (question_type::text = ANY (ARRAY['rc_question'::character varying::text, 'true_false'::character varying::text, 'inference'::character varying::text, 'tone'::character varying::text, 'purpose'::character varying::text, 'detail'::character varying::text, 'para_jumble'::character varying::text, 'para_summary'::character varying::text, 'para_completion'::character varying::text, 'critical_reasoning'::character varying::text, 'vocab_in_context'::character varying::text, 'odd_one_out'::character varying::text])),
  options jsonb,
  correct_answer jsonb NOT NULL,
  jumbled_sentences jsonb,
  rationale text NOT NULL,
  rationale_model character varying,
  hints jsonb,
  difficulty character varying CHECK (difficulty::text = ANY (ARRAY['easy'::character varying, 'medium'::character varying, 'hard'::character varying, 'expert'::character varying]::text[])),
  tags ARRAY,
  quality_score numeric,
  times_answered integer DEFAULT 0,
  times_correct integer DEFAULT 0,
  avg_time_seconds integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  paper_id uuid,
  CONSTRAINT questions_pkey PRIMARY KEY (id),
  CONSTRAINT questions_paper_id_fkey FOREIGN KEY (paper_id) REFERENCES public.exam_papers(id),
  CONSTRAINT questions_passage_id_fkey FOREIGN KEY (passage_id) REFERENCES public.passages(id)
);
CREATE TABLE public.reasoning_steps (
  key text NOT NULL,
  label text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT reasoning_steps_pkey PRIMARY KEY (key)
);
CREATE TABLE public.social_activity_feed (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  activity_type character varying NOT NULL CHECK (activity_type::text = ANY (ARRAY['achievement_unlocked'::character varying, 'streak_milestone'::character varying, 'challenge_completed'::character varying, 'leaderboard_rank'::character varying, 'group_joined'::character varying, 'practice_completed'::character varying]::text[])),
  activity_data jsonb NOT NULL,
  is_public boolean DEFAULT true,
  likes_count integer DEFAULT 0,
  comments_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT social_activity_feed_pkey PRIMARY KEY (id),
  CONSTRAINT social_activity_feed_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.study_group_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  group_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role character varying DEFAULT 'member'::character varying CHECK (role::text = ANY (ARRAY['admin'::character varying, 'moderator'::character varying, 'member'::character varying]::text[])),
  last_active_at timestamp with time zone,
  messages_sent integer DEFAULT 0,
  sessions_participated integer DEFAULT 0,
  joined_at timestamp with time zone DEFAULT now(),
  CONSTRAINT study_group_members_pkey PRIMARY KEY (id),
  CONSTRAINT study_group_members_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.study_groups(id),
  CONSTRAINT study_group_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.study_groups (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  description text,
  avatar_url text,
  is_private boolean DEFAULT false,
  join_code character varying UNIQUE,
  max_members integer DEFAULT 50,
  created_by uuid NOT NULL,
  admin_ids ARRAY,
  member_count integer DEFAULT 0,
  active_sessions integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT study_groups_pkey PRIMARY KEY (id),
  CONSTRAINT study_groups_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.system_metrics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  metric_date date NOT NULL UNIQUE,
  total_users integer DEFAULT 0,
  active_users_today integer DEFAULT 0,
  new_signups integer DEFAULT 0,
  passages_generated integer DEFAULT 0,
  questions_generated integer DEFAULT 0,
  ai_generation_cost_cents integer DEFAULT 0,
  avg_api_latency_ms integer,
  error_rate numeric,
  total_practice_sessions integer DEFAULT 0,
  total_questions_attempted integer DEFAULT 0,
  avg_session_duration_minutes integer,
  appeal_rate numeric,
  content_approval_rate numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.theory_chunks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  topic text NOT NULL,
  sub_topic text NOT NULL,
  concept_title text NOT NULL,
  content text NOT NULL,
  source_pdf text,
  page_number integer,
  example_text text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT theory_chunks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_analytics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  minutes_practiced integer DEFAULT 0,
  questions_attempted integer DEFAULT 0,
  questions_correct integer DEFAULT 0,
  accuracy_percentage numeric,
  is_active_day boolean DEFAULT false,
  current_streak integer DEFAULT 0,
  longest_streak integer DEFAULT 0,
  points_earned_today integer DEFAULT 0,
  total_points integer DEFAULT 0,
  genre_performance jsonb,
  difficulty_performance jsonb,
  question_type_performance jsonb,
  new_words_learned integer DEFAULT 0,
  words_reviewed integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_active_date date,
  CONSTRAINT user_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT user_analytics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.user_metric_proficiency (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  dimension_type text NOT NULL CHECK (dimension_type = ANY (ARRAY['core_metric'::text, 'genre'::text, 'question_type'::text, 'reasoning_step'::text, 'error_pattern'::text])),
  dimension_key text NOT NULL,
  proficiency_score integer NOT NULL CHECK (proficiency_score >= 0 AND proficiency_score <= 100),
  confidence_score numeric NOT NULL CHECK (confidence_score >= 0::numeric AND confidence_score <= 1::numeric),
  total_attempts integer NOT NULL DEFAULT 0,
  correct_attempts integer NOT NULL DEFAULT 0,
  last_session_id uuid,
  trend text CHECK (trend = ANY (ARRAY['improving'::text, 'declining'::text, 'stagnant'::text])),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  speed_vs_accuracy_data jsonb,
  CONSTRAINT user_metric_proficiency_pkey PRIMARY KEY (id),
  CONSTRAINT user_metric_proficiency_user_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.user_proficiency_signals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  overall_percentile integer CHECK (overall_percentile >= 0 AND overall_percentile <= 100),
  estimated_cat_percentile integer CHECK (estimated_cat_percentile >= 0 AND estimated_cat_percentile <= 100),
  genre_strengths jsonb,
  inference_skill integer CHECK (inference_skill >= 0 AND inference_skill <= 100),
  tone_analysis_skill integer CHECK (tone_analysis_skill >= 0 AND tone_analysis_skill <= 100),
  main_idea_skill integer CHECK (main_idea_skill >= 0 AND main_idea_skill <= 100),
  detail_comprehension_skill integer CHECK (detail_comprehension_skill >= 0 AND detail_comprehension_skill <= 100),
  recommended_difficulty character varying,
  weak_topics ARRAY,
  weak_question_types ARRAY,
  calculated_at timestamp with time zone DEFAULT now(),
  data_points_count integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_proficiency_signals_pkey PRIMARY KEY (id),
  CONSTRAINT user_proficiency_signals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  username character varying NOT NULL UNIQUE,
  display_name character varying,
  avatar_url text,
  subscription_tier character varying DEFAULT 'free'::character varying CHECK (subscription_tier::text = ANY (ARRAY['free'::character varying, 'pro'::character varying, 'premium'::character varying]::text[])),
  subscription_expires_at timestamp with time zone,
  daily_goal_minutes integer DEFAULT 30,
  preferred_difficulty character varying DEFAULT 'medium'::character varying CHECK (preferred_difficulty::text = ANY (ARRAY['easy'::character varying, 'medium'::character varying, 'hard'::character varying, 'adaptive'::character varying]::text[])),
  theme character varying DEFAULT 'light'::character varying CHECK (theme::text = ANY (ARRAY['light'::character varying, 'dark'::character varying, 'auto'::character varying]::text[])),
  data_consent_given boolean DEFAULT false,
  show_on_leaderboard boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_active_at timestamp with time zone DEFAULT now(),
  email text UNIQUE,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_vocab_progress (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  vocab_id uuid NOT NULL,
  mastery_level integer DEFAULT 0 CHECK (mastery_level >= 0 AND mastery_level <= 5),
  times_reviewed integer DEFAULT 0,
  times_correct integer DEFAULT 0,
  times_incorrect integer DEFAULT 0,
  next_review_at timestamp with time zone DEFAULT now(),
  ease_factor numeric DEFAULT 2.5,
  interval_days integer DEFAULT 1,
  first_encountered_passage_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  last_reviewed_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_vocab_progress_pkey PRIMARY KEY (id),
  CONSTRAINT user_vocab_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT user_vocab_progress_vocab_id_fkey FOREIGN KEY (vocab_id) REFERENCES public.vocab_entries(id),
  CONSTRAINT user_vocab_progress_first_encountered_passage_id_fkey FOREIGN KEY (first_encountered_passage_id) REFERENCES public.passages(id)
);
CREATE TABLE public.vocab_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  word character varying NOT NULL UNIQUE,
  word_normalized character varying NOT NULL,
  definition jsonb NOT NULL,
  part_of_speech character varying,
  difficulty_level character varying CHECK (difficulty_level::text = ANY (ARRAY['basic'::character varying, 'intermediate'::character varying, 'advanced'::character varying, 'expert'::character varying]::text[])),
  mnemonic text,
  breakdown text,
  synonyms ARRAY,
  antonyms ARRAY,
  etymology text,
  generated_by_model character varying,
  generation_cost_cents integer,
  times_looked_up integer DEFAULT 0,
  times_practiced integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vocab_entries_pkey PRIMARY KEY (id)
);