import React from 'react';
import { ClipboardLogo } from '../../../ui_components/ClipboardLogo';
import { FeatureList } from '../../../ui_components/FeatureCard';
import { defaultFeatures } from '../../../ui_components/FeatureTypes';
import type { Feature } from '../../../ui_components/FeatureTypes';
import { CollapsibleSidebar } from '../../../ui_components/CollapsibleSidebar';
import { Footer } from '../../../ui_components/Footer';

export const HomePage: React.FC = () => {
  const handleFeatureClick = (feature: Feature) => {
    // TODO: Implement navigation to specific feature pages
    console.log(`Navigating to: ${feature.path}`);
    // This would trigger routing when backend is connected
  };

  return (
    <div className="min-h-screen bg-bg-primary">
      {/* Collapsible Sidebar */}
      <CollapsibleSidebar />
      
      {/* Main Content Area */}
      <div className="ml-64 transition-all duration-300">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          
          {/* Hero Section */}
          <div className="text-center mb-16 pt-8">
            <div className="flex flex-col lg:flex-row items-center justify-center gap-12 mb-12">
              
              {/* Logo Section */}
              <div className="flex-1 flex justify-center">
                <div className="relative">
                  <ClipboardLogo 
                    size={300} 
                    animated={true}
                    className="drop-shadow-2xl hover:scale-105 transition-transform duration-300"
                  />
                  
                  {/* Subtle floating elements */}
                  <div className="absolute -top-4 -right-4 w-6 h-6 bg-accent-success rounded-full animate-bounce-subtle opacity-70"></div>
                  <div className="absolute -bottom-2 -left-6 w-4 h-4 bg-accent-warning rounded-full animate-pulse-slow opacity-60"></div>
                </div>
              </div>

              {/* Brand and Tagline */}
              <div className="flex-1 space-y-6">
                <div className="space-y-4">
                  <h1 className="text-6xl lg:text-7xl font-bold bg-gradient-to-r from-accent-primary via-accent-secondary to-accent-primary bg-clip-text text-transparent leading-tight">
                    PrepToDo
                  </h1>
                  <p className="text-2xl lg:text-3xl text-text-secondary font-medium">
                    Your AI-Powered Study Companion
                  </p>
                </div>
                
                <div className="max-w-lg mx-auto lg:mx-0">
                  <p className="text-lg text-text-muted leading-relaxed">
                    Transform your learning journey with intelligent study plans, 
                    adaptive practice tests, and comprehensive analytics.
                  </p>
                </div>

                {/* CTA Buttons */}
                <div className="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start pt-4">
                  <button className="
                    px-8 py-4 bg-gradient-to-r from-accent-primary to-accent-secondary 
                    text-white font-semibold rounded-xl hover:shadow-medium 
                    transform hover:-translate-y-1 transition-all duration-300
                    focus:outline-none focus:ring-2 focus:ring-accent-primary focus:ring-offset-2
                  ">
                    Get Started
                  </button>
                  <button className="
                    px-8 py-4 border-2 border-border-primary text-text-primary 
                    font-semibold rounded-xl hover:border-accent-primary hover:text-accent-primary
                    transform hover:-translate-y-1 transition-all duration-300
                    focus:outline-none focus:ring-2 focus:ring-accent-primary focus:ring-offset-2
                  ">
                    Watch Demo
                  </button>
                </div>
              </div>
            </div>
          </div>

          {/* Introduction Section */}
          <div className="mb-20">
            <div className="max-w-4xl mx-auto text-center space-y-8">
              <h2 className="text-4xl lg:text-5xl font-bold text-text-primary">
                Revolutionizing Education Through 
                <span className="bg-gradient-to-r from-accent-primary to-accent-secondary bg-clip-text text-transparent"> AI</span>
              </h2>
              
              <div className="space-y-6 text-lg text-text-secondary leading-relaxed">
                <p>
                  PrepToDo is a cutting-edge educational platform that harnesses the power of artificial intelligence 
                  to create personalized learning experiences. Even though all our study materials are generated by AI, 
                  our platform excels in the way it analyzes and helps users grow overall.
                </p>
                
                <p>
                  Our sophisticated algorithms don't just create content—they understand your unique learning style, 
                  track your progress in real-time, and adapt your study journey to maximize retention and performance. 
                  Every interaction is designed to build upon your existing knowledge while identifying and strengthening 
                  weak areas.
                </p>
                
                <p className="text-accent-primary font-medium">
                  ✨ The result? A study experience that's not just personalized, but truly transformative—
                  helping you achieve better grades, deeper understanding, and lasting knowledge retention.
                </p>
              </div>

              {/* Trust indicators */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-8 pt-12">
                <div className="text-center space-y-2">
                  <div className="text-3xl font-bold text-accent-primary">95%</div>
                  <div className="text-text-muted">Student Satisfaction</div>
                </div>
                <div className="text-center space-y-2">
                  <div className="text-3xl font-bold text-accent-secondary">2x</div>
                  <div className="text-text-muted">Faster Learning</div>
                </div>
                <div className="text-center space-y-2">
                  <div className="text-3xl font-bold text-accent-success">24/7</div>
                  <div className="text-text-muted">AI Support</div>
                </div>
              </div>
            </div>
          </div>

          {/* Features Section */}
          <div className="mb-20">
            <div className="text-center mb-12">
              <h2 className="text-4xl lg:text-5xl font-bold text-text-primary mb-4">
                Powerful Features for 
                <span className="bg-gradient-to-r from-accent-primary to-accent-secondary bg-clip-text text-transparent"> Success</span>
              </h2>
              <p className="text-xl text-text-secondary max-w-3xl mx-auto">
                Discover how PrepToDo's comprehensive suite of AI-powered tools can transform 
                your study experience and accelerate your academic growth.
              </p>
            </div>
            
            <FeatureList 
              features={defaultFeatures} 
              onFeatureClick={handleFeatureClick}
              className="mb-12"
            />
          </div>

          {/* Call to Action Section */}
          <div className="text-center py-16 bg-gradient-to-r from-accent-primary/10 to-accent-secondary/10 rounded-2xl border border-border-primary mb-16">
            <h2 className="text-3xl lg:text-4xl font-bold text-text-primary mb-4">
              Ready to Transform Your Study Experience?
            </h2>
            <p className="text-lg text-text-secondary mb-8 max-w-2xl mx-auto">
              Join thousands of students who have already revolutionized their learning journey with PrepToDo. 
              Start your personalized AI-powered study plan today.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <button className="
                px-8 py-4 bg-gradient-to-r from-accent-primary to-accent-secondary 
                text-white font-semibold rounded-xl hover:shadow-medium 
                transform hover:-translate-y-1 transition-all duration-300
                focus:outline-none focus:ring-2 focus:ring-accent-primary focus:ring-offset-2
              ">
                Start Free Trial
              </button>
              <button className="
                px-8 py-4 border-2 border-border-primary text-text-primary 
                font-semibold rounded-xl hover:border-accent-primary hover:text-accent-primary
                transform hover:-translate-y-1 transition-all duration-300
                focus:outline-none focus:ring-2 focus:ring-accent-primary focus:ring-offset-2
              ">
                View Pricing
              </button>
            </div>
          </div>
        </div>

        {/* Footer */}
        <Footer />
      </div>
    </div>
  );
};